### ISSUE TITLE
Documentation - Test Explorer

### ISSUE THREAD

**Issue by Pinox** [thomhurst/TUnit#1302]
I followed the Tutorial Basics and immediately hit my first obstacle.

Test explorer in Visual Studio is not working and that is a show stopper for me. After searching online I eventually found a comment that the xunit template can be used with tunit and then the test explorer work again.

![image](https://github.com/user-attachments/assets/af793986-cf10-43d0-ad6e-9ed0fce0a68c)

with project file as follows:
![image](https://github.com/user-attachments/assets/145c1553-85fe-4991-924a-60f2ae8ac826)

Would be great if you guys include this test explorer setup screen with the Visual Studio settings screenshot in the basics tutorial as I think a lot of people like me will be looking for this as that is what we are accustomed to using inside visual studio.

**Comment by thomhurst** [comment]
Where did you read this comment? You do not need the xunit runner. You probably just haven't turned on the testing platform mode as detailed here: https://thomhurst.github.io/TUnit/docs/tutorial-basics/running-your-tests#visual-studio

**Comment by Pinox** [comment]
@thomhurst 

https://learn.microsoft.com/en-us/answers/questions/2078124/tunit-test-is-not-showing-in-the-test-explorer


Testing platform did not work for me on its own.

**Comment by thomhurst** [comment]
They're mixing xUnit and TUnit in one project, which is not supported, they will conflict with each other.

> Testing platform did not work for me on its own.

Did you restart Visual Studio after?

Also, Coverlet is not supported for TUnit, you need to use: `Microsoft.Testing.Extensions.CodeCoverage`

**Comment by Pinox** [comment]
> Did you restart Visual Studio after?

No, I did not as it was already selected in my settings.

I initially got this error message but I see you are right if I now restart a new Visual Studio project with the normal packs then it works.

![image](https://github.com/user-attachments/assets/f9c8c891-539d-4167-ae52-88d14f2bc3f9)



========== Starting test discovery ==========
Test framework UID: 'TUnitExtension' Version: '0.4.1.0' DisplayName: 'TUnit' Description: 'TUnit Framework for Microsoft Testing Platform'
System.IO.IOException: The device is not ready. : '000.testlog'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at Microsoft.VisualStudio.TestStorage.TestLog.WriteLogEntry(LogEntry logEntry)
   at Microsoft.VisualStudio.TestStorage.TestLog.Append(TestBaseRecord testRecord)
   at Microsoft.VisualStudio.TestStorage.TestStore.AddToLog(TestBaseRecord record)
   at Microsoft.VisualStudio.TestStorage.TestStore.Add(TestBaseRecord record, Boolean onlyAddIfNew)
   at Microsoft.VisualStudio.TestWindow.Host.TestRunSessionBase.AddTestCases(ICollection`1 testCaseRecords)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.AddRemoteTestCaseRecords(IEnumerable`1 testCases)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.OnTestsDiscovered(IEnumerable`1 testsDiscovered)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallInternalWithLogging[TArg](IInternalLogger log, Action`1 action, TArg arg, Boolean shouldThrow)
System.IO.IOException: The device is not ready. : '\TestStore\0\000.testlog'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at Microsoft.VisualStudio.TestStorage.TestLog.WriteLogEntry(LogEntry logEntry)
   at Microsoft.VisualStudio.TestStorage.TestLog.Append(TestBaseRecord testRecord)
   at Microsoft.VisualStudio.TestStorage.TestStore.AddToLog(TestBaseRecord record)
   at Microsoft.VisualStudio.TestStorage.TestStore.Add(TestBaseRecord record, Boolean onlyAddIfNew)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.OnDiscoveryCompletedForContainer(TestContainerRecord container, IEnumerable`1 activeEnvironments)
   at Microsoft.VisualStudio.TestWindow.Host.VsTestRunSession.OnDiscoveryCompleted(IEnumerable`1 containersSentForDiscovery, IEnumerable`1 activeEnvironments)
   at Microsoft.VisualStudio.TestWindow.Host.TestPlatformProvider.DiscoverTestsAsync(DiscoverTestsRequest request, TestStore testStore, VsTestRunSession runSession, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass42_0.<<DiscoverTestsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---

**Comment by thomhurst** [comment]
Glad it's working now

**Comment by Arthri** [comment]
> Also, Coverlet is not supported for TUnit, you need to use: `Microsoft.Testing.Extensions.CodeCoverage`

For what it's worth, `coverlet.console` seems to work with TUnit. But `coverlet.msbuild` requires a few tweaks, which I've detailed in the issue I wrote https://github.com/coverlet-coverage/coverlet/issues/1715
