### ISSUE TITLE
Include inner exceptions when tests fail.

### ISSUE THREAD

**Issue by benjaminsampica** [thomhurst/TUnit#1327]
It would be helpful to include inner exceptions in the test failure if possible. I'm thinking like when using EF Core and you have a foreign key conflict, currently the library only spits out the following:

```
An error occurred while saving the entity changes. See the inner exception for details.
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at SendTrucks.Ui.Tests.IntegrationTestBase.AddAsync[TEntity](TEntity entity) in /Users/benjaminsampica/Repos/sendtrucks/src/SendTrucks.Ui.Tests/IntegrationTestBase.cs:line 96
   at SendTrucks.Ui.Tests.Features.Loads.Detail.Dispatches.Records.Detail.ExportTests.GivenIWantToExport_WhenTheDispatchExists_ThenExports() in /Users/benjaminsampica/Repos/sendtrucks/src/SendTrucks.Ui.Tests/Features/Loads/Detail/Dispatches/Records/Detail/ExportTests.cs:line 13
   at TUnit.Core.AsyncConvert.Convert(Func`1 action)
   at TUnit.Core.DiscoveredTest`1.ExecuteTest(CancellationToken cancellationToken)
   at TUnit.Engine.Helpers.Timings.Record(String name, TestContext context, Func`1 action)
   at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
   at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestMethodWithTimeout(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithCancellationTokens(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
   at TUnit.Engine.Services.TestsExecutor.ProcessTest(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, CancellationToken cancellationToken)
```

Of course, this can be waved away with hooking via after test and pulling it out but having it be baked in would be great.

**Comment by thomhurst** [comment]
This is actually a Testing Platform issue. I send an object to the testing platform with the raw exception on it. Since output is handled by either them, or the IDE, then they need to output it correctly.

**Comment by thomhurst** [comment]
I did actually raise this on the testing platform a while back, but it should've been sorted and in the current release: https://github.com/microsoft/testfx/issues/3783

Where are you looking at this output? CLI / VS / Rider?

**Comment by benjaminsampica** [comment]
Interesting! I'm seeing this in Rider via the test explorer window.

**Comment by thomhurst** [comment]
It might be a Rider issue then. I'm actually not sure if it's testing platform or rider to be honest!

**Comment by thomhurst** [comment]
The CLI seems to show them properly. But Rider and VS don't. Not sure if both have issues or not.

**Comment by thomhurst** [comment]
@Evangelink @nohwnd Do you happen to know?

**Comment by Evangelink** [comment]
I'll double check VS behavior and what the platform sends and get back to you.

**Comment by Evangelink** [comment]
I believe this is working fine on platform level.

My MSTest code:

```csharp
[TestClass]
public class TestClass
{
    [TestMethod]
    public void Test3()
    {
        try
        {
            try
            {
                Throw();
            }
            catch (Exception ex)
            {
                throw new Exception("inner", ex);
            }
        }
        catch (Exception ex)
        {
            throw new Exception("root", ex);
        }
    }

    private void Throw() => throw new Exception("bottom");
}
```

The output in Test Explorer:
![image](https://github.com/user-attachments/assets/9495722d-8330-48d6-a159-595c4fa38aeb)

Console output:
![image](https://github.com/user-attachments/assets/7d2e1d1c-5f56-4845-b192-a0935dbe930b)

**Comment by thomhurst** [comment]
It shows in TUnit console too:

```
failed Test3 (61ms)
  System.Exception: root
    at TestClass.Test3() in Program.cs:19
    at TUnit.SourceGenerated.<TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f_Generated>F9A1DAB0743430E24826D0CC045A343AE06EDBD6B3496FB02F9E90B56294935FD__TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f.<>c__DisplayClass2_2.<Tests0>b__3() in obj\Debug\net8.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f.Generated.cs:51
    at TUnit.SourceGenerated.<TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f_Generated>F9A1DAB0743430E24826D0CC045A343AE06EDBD6B3496FB02F9E90B56294935FD__TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f.<>c.<Tests0>b__2_2(TestClass classInstance, CancellationToken cancellationToken) in obj\Debug\net8.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\TestClass__ConsoleApp8_e7893e468b134cb5a0d9c378b0c3ea7f.Generated.cs:51
    at TUnit.Core.TestMetadata`1.<BuildDiscoveredTest>b__11_0(TClassType classInstance, CancellationToken cancellationToken)
    at TUnit.Core.DiscoveredTest`1.<>c__DisplayClass8_0.<ExecuteTest>b__0()
    at TUnit.Core.DefaultExecutor.ExecuteAsync(Func`1 action)
    at TUnit.Core.GenericAbstractExecutor.ExecuteTest(TestContext context, Func`1 action)
    at TUnit.Core.DiscoveredTest`1.ExecuteTest(CancellationToken cancellationToken)
    at TUnit.Engine.Helpers.Timings.Record(String name, TestContext context, Func`1 action)
    at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestMethodWithTimeout(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithCancellationTokens(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
    at TUnit.Engine.Services.TestsExecutor.ProcessTest(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, CancellationToken cancellationToken)
  --->  System.Exception: inner
    at TestClass.Test3() in Program.cs:14
  --->  System.Exception: bottom
    at TestClass.Throw() in Program.cs:23
    at TestClass.Test3() in Program.cs:10
```

It doesn't in Rider, but since the CLI is fine, I'd go with it being a Rider issue

**Comment by Evangelink** [comment]
I don't have contact on Rider side, do you have some @thomhurst?

**Comment by thomhurst** [comment]
Not a specific contact, but I can raise on YouTrack and they can triage it

**Comment by benjaminsampica** [comment]
@thomhurst do you have a link to the Youtrack issue? Otherwise I can open one and this can probably be closed here.

**Comment by thomhurst** [comment]
@benjaminsampica I'm so sorry I completely forgot about this. I never raised one. Are you okay to do so if it's still affecting you?

**Comment by benjaminsampica** [comment]
I'll close this. YouTrack ticket -> [here](https://youtrack.jetbrains.com/issue/RIDER-122520/No-inner-exception-details-when-a-test-fails-while-using-Microsoft.Testing.Platform)

**Comment by ZhakaTaka** [comment]
Looks like there is the same problem with TUnit in Visual Studio.
I use [this code](https://github.com/thomhurst/TUnit/issues/1327#issuecomment-2520689678)

According to the documentation [error.message](https://github.com/microsoft/testfx/blob/main/docs/mstest-runner-protocol/001-protocol-intro.md#discovery-of-tests:~:text=The%20error%20consists%20of%20the%20stacktrace%2C%20error%20message%20and%20also%20the%20assertion%20properties.) field should be filled with the exception details. In our case it contains only "Exception: root".

<img width="2442" height="762" alt="Image" src="https://github.com/user-attachments/assets/b2a231d0-0b6c-4a04-a373-423f2b7592b0" />

**Comment by koryphaee** [comment]
There have been new developments in the Rider issue tracker here: https://youtrack.jetbrains.com/issue/RSRP-499947/No-inner-exception-details-when-a-test-fails-while-using-Microsoft.Testing.Platform
Looks like this issue needs to be re-opened because the problem lies with TUnit side, not Rider.

**Comment by koryphaee** [comment]
Thank you <3
