### ISSUE TITLE
ClassDataSource instance shared "PerTestSession" and "Keyed" disposed too early when test has [DependsOn]

### ISSUE THREAD

**Issue by skoging** [thomhurst/TUnit#1410]
Version: `0.4.105`

When running a specific test (either from an IDE test explorer or with `--treenode-filter`) that has a `[DependsOn]` dependency, `ClassDataSource` instances with `SharedType.PerTestSession` or `SharedType.Keyed` are disposed too early:

```
Remaining tests has gone below 0 for Type {TestClass}
```

It seems like the counter for the number of tests that are expected to be executed are incorrect, as it does not take additional tests due to`[DependsOn]` into account.

```cs
public class ReproFixture : IDisposable
{
    public bool IsDisposed { get; private set; } = false;

    public void Dispose()
    {
        IsDisposed = true;
    }
}


[ClassDataSource<ReproFixture>(Shared = SharedType.PerTestSession)]
public class ReproTest(ReproFixture fixture)
{
    [Test]
    public async Task ReproTest1()
    {
        await Assert.That(fixture.IsDisposed).IsFalse();
    }
    
    [Test, DependsOn(nameof(ReproTest1))]
    public async Task ReproTest2()
    {
        await Assert.That(fixture.IsDisposed).IsFalse();
    }
}
```

<details><summary>Test output</summary>
<p>

```
❯ dotnet run --no-build --treenode-filter "/*/*/*/ReproTest2"    

████████╗██╗   ██╗███╗   ██╗██╗████████╗
╚══██╔══╝██║   ██║████╗  ██║██║╚══██╔══╝
   ██║   ██║   ██║██╔██╗ ██║██║   ██║   
   ██║   ██║   ██║██║╚██╗██║██║   ██║   
   ██║   ╚██████╔╝██║ ╚████║██║   ██║   
   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚═╝   ╚═╝   
   
   TUnit v0.4.105.0 | 64-bit | Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 | osx-arm64 | .NET 9.0.0 | Microsoft Testing Platform v1.4.3
   
failed ReproTest2 (1ms)
  System.AggregateException: One or more errors occurred. (Expected fixture.IsDisposed to be equal to False
  
  but found True
  
  at Assert.That(fixture.IsDisposed).IsFalse()) (Remaining tests has gone below 0 for Type Tests.End2End.ReproTest)
  --->  TUnit.Assertions.Exceptions.AssertionException: Expected fixture.IsDisposed to be equal to False
  
  but found True
  
  at Assert.That(fixture.IsDisposed).IsFalse()
    at TUnit.Assertions.AssertionBuilders.AssertionBuilder`1.ProcessAssertionsAsync()
    at TUnit.Assertions.AssertionBuilders.InvokableValueAssertionBuilder`1.AssertAndGet()
    at Tests.End2End.ReproTest.ReproTest2() in Repro.cs:26
    at TUnit.Core.AsyncConvert.Convert(Func`1 action)
    at TUnit.Core.DiscoveredTest`1.ExecuteTest(CancellationToken cancellationToken)
    at TUnit.Engine.Helpers.Timings.Record(String name, TestContext context, Func`1 action)
    at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestMethodWithTimeout(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithCancellationTokens(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
  --->  System.Exception: Remaining tests has gone below 0 for Type Tests.End2End.ReproTest
    at TUnit.Engine.InstanceTracker.IsLastTestForType(Type type)
    at TUnit.Engine.Hooks.ClassHookOrchestrator.CollectAfterHooks(TestContext testContext, Type testClassType)+MoveNext()
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteStaticAfterHooks(DiscoveredTest test, TestContext testContext, List`1 cleanUpExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.RunCleanUps(DiscoveredTest test, TestContext testContext, List`1 cleanUpExceptions)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
    at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
    at TUnit.Engine.Services.TestsExecutor.ProcessTest(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, CancellationToken cancellationToken)

Test run summary: Failed! - bin/Debug/net9.0/Tests.End2End.dll (net9.0|arm64)
  total: 2
  failed: 1
  succeeded: 1
  skipped: 0
  duration: 123ms
```
</p>
</details>

**Comment by skoging** [comment]
Same issue occurs with `SharedType.Keyed`
