### ISSUE TITLE
DirectoryNotFoundException: Error executing Before(TestSession) method

### ISSUE THREAD

**Issue by rigtigeEmil** [thomhurst/TUnit#811]
When running the application directly through IDE (Rider), the tests run and work as expected. When running `dotnet test` from the folder where the test project is located, this exception is thrown:
```
TUnit.Core.Exceptions.BeforeTestSessionException: Error executing Before(TestSession) method: GilbertBffApiTestBase.PrepareSession()
 ---> System.IO.DirectoryNotFoundException: C:\git\Gilbert\Gilbert.API.BFF\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateHostingEnvironment(IConfiguration hostConfiguration)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Initialize(HostApplicationBuilderSettings settings, HostBuilderContext& hostBuilderContext, IHostEnvironment& environment, LoggingBuilder& logging, MetricsBuilder& metrics)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in C:\git\Gilbert\src\Gilbert.API.BFF\Program.cs:line 32
   at Program.<Main>(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

Which makes sense, since it's looking in the wrong folder. The real path is `C:\git\src\Gilbert.API.BFF\` (where `Gilbert.API.BFF.csproj` is located).
 The test project is referencing the API like this:
```
<ItemGroup>
  <ProjectReference Include="..\..\src\Gilbert.API.BFF\Gilbert.API.BFF.csproj" />
</ItemGroup>
```
The test project is located in `C:\git\Gilbert\tests\Gilbert.Tests.API.BFF\Gilbert.Tests.API.BFF.csproj`

**Comment by thomhurst** [comment]
What code is in your before hook?

**Comment by rigtigeEmil** [comment]
Eh, "nothing", just something that accesses the underlying `WebApplicationFactory` for the first time, so I guess that's why it throws on that line.
So it's doing this:
```cs
[Before(TestSession)]
public static async Task PrepareSession()
{
    var documentStore = Factory.Services.GetRequiredService<IDocumentStore>();
    // do something with the document store
}

```

**Comment by thomhurst** [comment]
Hmmm I don't know what that web builder is doing under the hood. Before it hits can you breakpoint and see what both TestContext.OutputDirectory and TestContext.WorkingDirectory are?

**Comment by rigtigeEmil** [comment]
output: C:\git\Gilbert\tests\Gilbert.Tests.API.BFF\bin\Debug\net8.0
working: C:\git\Gilbert\tests\Gilbert.Tests.API.BFF

**Comment by rigtigeEmil** [comment]
^this is not from debug, but just from 
```
Console.WriteLine(TestContext.OutputDirectory);
Console.WriteLine(TestContext.WorkingDirectory);
```

**Comment by thomhurst** [comment]
Does setting the working to the same value as the output fix it?

**Comment by rigtigeEmil** [comment]
Yep 😁

**Comment by thomhurst** [comment]
I'll make TUnit default to the assembly's current location. I think that's what most people would expect.
